#!/bin/bash
# Helper ANSI colors
RED='\033[0;31m'
NC='\033[0m' # No Color
USE_NVIM=1 # No Color
USE_VIM=0 # No Color

# creates symlinks for desired files from home to specified directory

dir=~/dotfiles
olddir=~/.dotfiles.bak

# install GTK3 config
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then GNOME_CONFIG=".config/gtk-3.0"
    mkdir ~/$GNOME_CONFIG -p
    ln -s $dir/$GNOME_CONFIG/gtk.css ~/$GNOME_CONFIG/gtk.css
fi;

#install git-completion
cd $dir
curl https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -OL

# list of files/folders to symlink in homedir
declare -a files=(
"bashrc" "bash_profile" "bash_aliases" 
"vim"
"tmux.conf" 
"ctags"
"Xresources" "xinitrc"
)

echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
for file in "${files[@]}"; do
    if [ ! -f ~/.$file ]; then 
        cd $dir
        cd ~
        mv .$file $olddir
        echo "Creating symlink to $file in `pwd`"
        ln -s $dir/$file .$file &> /dev/null
    fi;
done

# Install VIM config
declare -a files=(
"vimrc" "nvimrc" 
)
cd ~
for file in "${files[@]}"; do
    if [ ! -f ~/.$file ]; then 
        ln -s $dir/vimconfig .$file &> /dev/null
    fi;
done

vim +PlugUpdate +qall

# tern_for_vim requirements
command -v npm &> /dev/null
if [ $? = 0 ]; then 
    pushd ~/.vim/plugged/tern_for_vim/
    npm install
    popd
else
    echo -e "${RED}*** ERROR: npm is not found${NC}"
fi;

# Install you-complete-me (VIM environments only)
if [ ${USE_VIM} = 1 ]; then 
    echo -e "Installing VIM stuff"
   # command -v cmake &> /dev/null
   # echo "Compiling YouCompleteMe binaries..."
   # command -v cmake &> /dev/null
   # if [ $? = 0 ]; then 
   #     pushd ~/.vim/plugged/YouCompleteMe
   #     ./install.py --tern-completer
   #     popd
   # else
   #     echo -e "${RED}*** ERROR: cmake is not found${NC}"
   # fi;
fi;


echo "Executing vim colorscheme install..."
exec $dir/vim/colors/install_colors

# install VIM-NVIM transistion
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc

