#!/bin/bash

# Helper ANSI colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color
USE_NVIM=1 

# creates symlinks for desired files from home to specified directory
dir=~/dotfiles
olddir=~/.dotfiles.bak

# list of files/folders to symlink in homedir
declare -a files=(
"agignore"
"ideavimrc"
"bashrc" "bash_profile" "bash_aliases"
"vim"
"tmux.conf" 
"Xresources" "xinitrc"
"Xmodmap"
)

echo -e "${YELLOW}Creating $olddir for backup of any existing dotfiles in home and copy files${NC}"
mkdir -p $olddir
for file in "${files[@]}"; do
    printf %b "   .$file..."
    if [ ! -f ~/.$file ]; then 
        cd $dir
        cd ~
        mv .$file $olddir &> /dev/null
        ln -s $dir/$file .$file &> /dev/null
        printf %b "${GREEN} OK${NC}\n"
    else
        printf %b "${YELLOW} skipped${NC}\n"
    fi;
done

# Install VIM config
echo -e "${YELLOW}Installing vim configs...${NC}"
declare -a files=(
"vimrc" 
)
cd ~
for file in "${files[@]}"; do
    printf %b "   .$file...${NC}"
    if [ ! -f ~/.$file ]; then 
        ln -s $dir/vimconfig .$file &> /dev/null
        printf %b "${GREEN} OK${NC}\n"
    else
        printf %b "${YELLOW} skipped${NC}\n"
    fi;
done

#install git-completion
printf %b "${YELLOW}Installing git completion...${NC}"
if [ ! -f $dir/git-completion.bash ]; then 
    cd $dir
    curl https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -OLs > /dev/null
    printf %b "${GREEN} OK${NC}\n"
else
    printf %b "${YELLOW} skipped${NC}\n"
fi;

# install GTK3 config
printf %b "${YELLOW}Disabling f10 for gnome-menu...${NC}"
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then 
    GNOME_CONFIG=".config/gtk-3.0"
    mkdir ~/$GNOME_CONFIG -p
    if [ ! -f ~/$GNOME_CONFIG/gtk.css ]; then 
        ln -s $dir/$GNOME_CONFIG/gtk.css ~/$GNOME_CONFIG/gtk.css
        printf %b "${GREEN} OK${NC}\n"
    else
        printf %b "${YELLOW} skipped${NC}\n"
    fi;
fi;

# Install sjl/t [minimalistic tasks! <3]
printf %b "${YELLOW}Installing minimalisic task manager [http://stevelosh.com/projects/t]...${NC}"
command -v t &> /dev/null
if [ $? = 127 ]; then 
    git clone https://github.com/sjl/t.git ~/.tasks/t  
    printf %b "${GREEN}OK${NC}\n"
else
    printf %b "${YELLOW}skipped${NC}\n"
fi;

## Install vim fancy colors
#echo -e "${YELLOW}Installing vim colorschemes...${NC}"
#bash $dir/vim/colors/install_colors

# Since we symlink both files...seems redundant TODO check if happens automatically
printf %b "${YELLOW}Creating nvim config...${NC}"
if [ ! -f ~/.config/nvim/init.vim ]; then 
mkdir -p ~/.config/nvim && touch ~/.config/nvim/init.vim 
cat <<'EOF' > ~/.config/nvim/init.vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
EOF
    printf %b "${GREEN}OK${NC}\n"
else
    printf %b "${YELLOW}skipped${NC}\n"
fi;

# Installing python debugging protocol for vim-vdebug
# Usage: python-debug <script.py>
#printf %b "${YELLOW}Installing python debugging tool for vdebug...${NC}"
#if [ ! -f ~/.local/bin/python-debug ]; then
#    cd /tmp && wget -qO- http://downloads.activestate.com/Komodo/releases/10.2.3/remotedebugging/Komodo-PythonRemoteDebugging-10.2.3-89902-linux-x86_64.tar.gz | tar xvz && mv /tmp/Komodo-PythonRemoteDebugging-10.2.3-89902-linux-x86_64/ ~/.python-debugger-client && mv ~/.python-debugger-client/pythonlib/dbgp ~/.python-debugger-client/
#cat <<'EOF' > ~/.local/bin/python-debug
##!/bin/bash
#python -S ~/.python-debugger-client/pydbgp -d localhost:9000 "$@"
#EOF
#    chmod +x ~/.local/bin/python-debug
#        printf %b "${GREEN} OK${NC}\n"
#    else
#        printf %b "${YELLOW} skipped${NC}\n"
#fi;

# Installing base16-shell
if [ ! -d ~/.config/base16-shell ]; then
    printf %b "${YELLOW}Installing base16-shell...${NC}\n"
    git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell && printf %b "${GREEN} OK${NC}\n"
fi;

printf %b "${GREEN}Finished.${NC}\n"
