#!/bin/bash

# Helper ANSI colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Dependencies
command -v wget > /dev/null 2>&1 || { echo >&2 "wget is not installed. Aborting..."; exit 1; }
command -v vim > /dev/null 2>&1 || { echo >&2 "vim is not installed. Aborting..."; exit 1; }

declare -a themes=(
"https://raw.githubusercontent.com/ryanpcmcquen/true-monochrome_vim/master/colors/true-monochrome.vim"
"https://raw.githubusercontent.com/xero/blaquemagick.vim/master/colors/blaquemagick.vim"
"https://raw.githubusercontent.com/raphamorim/lucario/master/colors/lucario.vim"
"https://raw.githubusercontent.com/gummesson/stereokai.vim/master/colors/stereokai.vim"
"https://raw.githubusercontent.com/fcpg/vim-fahrenheit/master/colors/fahrenheit.vim"
"https://raw.githubusercontent.com/scwood/vim-hybrid/master/colors/hybrid.vim"
);

colordir=~/dotfiles/vim/colors/
mkdir -p $colordir
pushd $colordir > /dev/null

for link in "${themes[@]}"
do
    printf "   $(basename $link)..."
    if [ ! -f $(basename $link) ]; then 
        wget -nv -N $link --quiet
        printf "${GREEN}OK${NC}\n"
    else
        printf "${YELLOW}already installed${NC}\n"
    fi;
done

popd > /dev/null
